CREATE DATABASE QUANLYDIEMTHI
GO 

USE QUANLYDIEMTHI
GO


--TAO BANG HOC SINH
CREATE TABLE HOCSINH(
	MAHS VARCHAR(20) PRIMARY KEY,
	TENHS VARCHAR(50),
	NGAYSINH DATETIME,
	LOP VARCHAR(20),
	GT VARCHAR(20),
)


--TAO BANG MONHOC
CREATE TABLE MONHOC(
	MAMH VARCHAR(20) PRIMARY KEY,
	TENMH VARCHAR(50)
)


-- TAO BANG BANGDIEM
CREATE TABLE BANGDIEM (
	MAHS VARCHAR(20),
	MAMH VARCHAR(20),
	DIEMTHI INT,
	NGATKT DATETIME,
	PRIMARY KEY(MAHS, MAMH),
	FOREIGN KEY(MAHS) REFERENCES HOCSINH(MAHS),
	FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)
)


-- TAO BANG GIAO VIEN
CREATE TABLE GIAOVIEN(
	MAGV VARCHAR(20) PRIMARY KEY,
	TENGV VARCHAR(20),
	SDT VARCHAR(10)
)


-- CHINH SUA BANG MON HOC BO SUNG THEM MAGV LAF KHOA NGOAI CUA MON HOC
ALTER TABLE MONHOC ADD MAGV VARCHAR(20)
ALTER TABLE MONHOC ADD CONSTRAINT FK_MAGV FOREIGN KEY (MAGV)

GO






