CREATE DATABASE QUANLYSINHVIEN
GO

USE QUANLYSINHVIEN

-- TAO BANG CLASS
CREATE TABLE CLASS(
 CLASSID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
 CLASSNAME VARCHAR(60) NOT NULL,
 STRARTDATE DATETIME NOT NULL,
 STATUS BIT 
 )

 --TAO BANG STUDENT
CREATE TABLE STUDENT(
STUDENTID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
STUDENTNAME VARCHAR(30) NOT NULL, 
ADDRESS VARCHAR(50),
PHONE VARCHAR(20),
STATUS BIT,
CLASS INT,
FOREIGN KEY (CLASSID) REFERENCES CLASS (CLASSID)
)

-- TAO BANG MARK
CREATE TABLE MARK (
MARKID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SUBID INT NOT NULL,
STUDENTID INT NOT NULL,
MARK FLOAT DEFAULT 0 CHECK (MARK BETWEEN 0 AND 10 EXAMTIMES TINYINT DEFAULT 1,
UNIQUE (SUBID, STUDENTID),
FOREIGN KEY (SUBID) REFERENCES SUBJECT (SUBID),
FOREIGN KEY (STUDENTID) REFERENCES STUDENT (STUDENTID)
)
GO 



